-- ============================================================
-- SEED: political_entities_expanded (200+ figur politik Indonesia)
-- Jalankan: psql -f 05_entities_expanded.sql
-- ============================================================
INSERT INTO political_entities
  (canonical_name, aliases, entity_type, party_affiliation, position, era, is_active)
VALUES
-- A. PRESIDEN & WAPRES
('Prabowo Subianto', ARRAY['Prabowo','Pak Prabowo','Presiden Prabowo','Bapak Prabowo'], 'president', 'Gerindra', 'Presiden RI ke-8', ARRAY['Era Prabowo'], true),
('Gibran Rakabuming Raka', ARRAY['Gibran','Wapres Gibran','Mas Gibran'], 'vp', 'PSI', 'Wakil Presiden RI', ARRAY['Era Prabowo'], true),
('Joko Widodo', ARRAY['Jokowi','Pak Jokowi','Presiden Jokowi','JW'], 'president', 'PDI-P', 'Presiden RI ke-7', ARRAY['Era Jokowi'], false),
('Ma''ruf Amin', ARRAY['Ma''ruf Amin','Kiai Ma''ruf','Wapres Ma''ruf'], 'vp', 'PKB', 'Wakil Presiden RI ke-13', ARRAY['Era Jokowi'], false),
('Jusuf Kalla', ARRAY['JK','Jusuf Kalla','Pak JK','Wapres JK'], 'vp', 'Golkar', 'Wakil Presiden RI ke-10/12', ARRAY['Era SBY','Era Jokowi'], false),
('Boediono', ARRAY['Boediono','Pak Boediono','Wapres Boediono'], 'vp', 'Independen', 'Wakil Presiden RI ke-11', ARRAY['Era SBY'], false),
('Susilo Bambang Yudhoyono', ARRAY['SBY','Pak SBY','Presiden SBY'], 'president', 'Demokrat', 'Presiden RI ke-6', ARRAY['Era SBY'], false),
('Megawati Soekarnoputri', ARRAY['Megawati','Bu Mega','Bu Megawati','Ketum PDIP'], 'president', 'PDI-P', 'Presiden RI ke-5', ARRAY['Era Megawati'], false),
('Hamzah Haz', ARRAY['Hamzah Haz','Wapres Hamzah'], 'vp', 'PPP', 'Wakil Presiden RI ke-9', ARRAY['Era Megawati'], false),
('Abdurrahman Wahid', ARRAY['Gus Dur','Abdurrahman Wahid','Presiden Gus Dur'], 'president', 'PKB', 'Presiden RI ke-4', ARRAY['Era Gus Dur'], false),
('Bacharuddin Jusuf Habibie', ARRAY['BJ Habibie','Habibie','Pak Habibie'], 'president', 'Independen', 'Presiden RI ke-3', ARRAY['Era Habibie'], false),
('Try Sutrisno', ARRAY['Try Sutrisno','Jenderal Try'], 'vp', 'Independen', 'Wakil Presiden RI ke-6', ARRAY['Era Orba'], false),
('Sudharmono', ARRAY['Sudharmono'], 'vp', 'Golkar', 'Wakil Presiden RI ke-5', ARRAY['Era Orba'], false),
('Umar Wirahadikusumah', ARRAY['Umar Wirahadikusumah'], 'vp', 'Golkar', 'Wakil Presiden RI ke-4', ARRAY['Era Orba'], false),
('Adam Malik', ARRAY['Adam Malik'], 'vp', 'Independen', 'Wakil Presiden RI ke-3', ARRAY['Era Orba'], false),
('Sri Sultan Hamengkubuwono IX', ARRAY['Sri Sultan','Hamengkubuwono IX'], 'vp', 'Independen', 'Wakil Presiden RI ke-2', ARRAY['Era Orba'], false),
('Mohammad Hatta', ARRAY['Bung Hatta','Hatta','Mohammad Hatta'], 'vp', 'Independen', 'Wakil Presiden RI ke-1', ARRAY['Era Soekarno'], false),
('Soekarno', ARRAY['Soekarno','Bung Karno','Presiden Soekarno'], 'president', 'PNI', 'Presiden RI ke-1', ARRAY['Era Soekarno'], false),
-- B. KABINET PRABOWO
('Hadi Tjahjanto', ARRAY['Hadi Tjahjanto','Jenderal Hadi'], 'minister', 'Independen', 'Menko Polhukam', ARRAY['Era Prabowo'], true),
('Agus Harimurti Yudhoyono', ARRAY['AHY','Agus Harimurti','Agus Yudhoyono'], 'minister', 'Demokrat', 'Menko Infrastruktur', ARRAY['Era Prabowo'], true),
('Airlangga Hartarto', ARRAY['Airlangga','Pak Airlangga'], 'minister', 'Golkar', 'Menko Perekonomian', ARRAY['Era Prabowo'], true),
('Zulkifli Hasan', ARRAY['Zulhas','Zulkifli Hasan','Pak Zulhas'], 'minister', 'PAN', 'Menko Pangan', ARRAY['Era Prabowo'], true),
('Budi Gunadi Sadikin', ARRAY['Budi Gunadi','BGS'], 'minister', 'Independen', 'Menko Kesehatan', ARRAY['Era Prabowo'], true),
('Sugiono', ARRAY['Sugiono','Pak Sugiono'], 'minister', 'Gerindra', 'Menlu', ARRAY['Era Prabowo'], true),
('Andi Amran Sulaiman', ARRAY['Andi Amran','Amran Sulaiman'], 'minister', 'PAN', 'Menteri Pertanian', ARRAY['Era Prabowo'], true),
('Budi Arie Setiadi', ARRAY['Budi Arie','Pak Budi Arie'], 'minister', 'PAN', 'Menteri Kominfo', ARRAY['Era Prabowo'], true),
('Dito Ariotedjo', ARRAY['Dito Ariotedjo','Pak Dito'], 'minister', 'Golkar', 'Menteri Pemuda', ARRAY['Era Prabowo'], true),
('Pratikno', ARRAY['Pratikno','Pak Pratikno','Sekneg Pratikno'], 'minister', 'Independen', 'Mensesneg', ARRAY['Era Jokowi','Era Prabowo'], true),
('Nusron Wahid', ARRAY['Nusron Wahid','Pak Nusron'], 'minister', 'Golkar', 'Menteri Agraria', ARRAY['Era Prabowo'], true),
-- C. TOKOH PARTAI
('Surya Paloh', ARRAY['Surya Paloh','Pak Surya Paloh'], 'party_official', 'NasDem', 'Ketua Dewan Pembina NasDem', ARRAY['Era Jokowi','Era Prabowo'], true),
('Muhaimin Iskandar', ARRAY['Cak Imin','Muhaimin Iskandar','Ketum PKB'], 'party_official', 'PKB', 'Ketua Umum PKB', ARRAY['Era Jokowi','Era Prabowo'], true),
('Ahmad Syaikhu', ARRAY['Syaikhu','Sekjen PKS'], 'party_official', 'PKS', 'Presiden PKS', ARRAY['Era Prabowo'], true),
('Wiranto', ARRAY['Wiranto','Pak Wiranto','Jenderal Wiranto'], 'party_official', 'Hanura', 'Ketua Umum Hanura', ARRAY['Era SBY','Era Jokowi'], false),
('Hidayat Nur Wahid', ARRAY['Hidayat Nur Wahid'], 'party_official', 'PKS', 'Presiden PKS (sebelumnya)', ARRAY['Era SBY'], false),
('Anas Urbaningrum', ARRAY['Anas Urbaningrum','Anas'], 'party_official', 'Demokrat', 'Ketum Demokrat (sebelumnya)', ARRAY['Era SBY'], false),
('Edhie Baskoro Yudhoyono', ARRAY['Edhie Baskoro','EBY'], 'party_official', 'Demokrat', 'Sekjen Demokrat (sebelumnya)', ARRAY['Era SBY'], false),
-- D. GUBERNUR & KEPALA DAERAH
('Anies Baswedan', ARRAY['Anies','Pak Anies','Gubernur Anies'], 'governor', 'Independen', 'Gubernur DKI Jakarta (sebelumnya)', ARRAY['Era Jokowi'], true),
('Basuki Tjahaja Purnama', ARRAY['Ahok','BTP','Basuki Tjahaja Purnama'], 'governor', 'PSI', 'Gubernur DKI Jakarta (sebelumnya)', ARRAY['Era Jokowi'], true),
('Dedi Mulyadi', ARRAY['Dedi Mulyadi','Kang Dedi'], 'governor', 'Gerindra', 'Gubernur Jawa Barat', ARRAY['Era Prabowo'], true),
('Ridwan Kamil', ARRAY['Ridwan Kamil','RK','Kang Emil'], 'governor', 'Golkar', 'Gubernur Jawa Barat (sebelumnya)', ARRAY['Era Jokowi'], true),
('Ganjar Pranowo', ARRAY['Ganjar','Pak Ganjar','Gubernur Ganjar'], 'governor', 'PDI-P', 'Gubernur Jawa Tengah (sebelumnya)', ARRAY['Era Jokowi'], true),
('Khofifah Indar Parawansa', ARRAY['Khofifah','Bu Khofifah'], 'governor', 'PKB', 'Gubernur Jawa Timur', ARRAY['Era Prabowo'], true),
('Pramono Anung', ARRAY['Pramono Anung','Pak Pramono'], 'governor', 'PDI-P', 'Gubernur DKI Jakarta', ARRAY['Era Prabowo'], true),
-- E. ANGGOTA DPR/MPR
('Puan Maharani', ARRAY['Puan','Bu Puan','Puan Maharani'], 'legislator', 'PDI-P', 'Ketua DPR RI', ARRAY['Era Jokowi','Era Prabowo'], true),
('Bambang Soesatyo', ARRAY['Bambang Soesatyo','Bamsoet','BS'], 'legislator', 'Golkar', 'Ketua MPR', ARRAY['Era Jokowi'], true),
('Fadli Zon', ARRAY['Fadli Zon','Pak Fadli Zon'], 'legislator', 'Gerindra', 'Wakil Ketua DPR', ARRAY['Era Jokowi'], true),
('Ahmad Doli Kurnia Tampubolon', ARRAY['Doli Kurnia','Ahmad Doli'], 'legislator', 'Golkar', 'Anggota DPR', ARRAY['Era Jokowi'], true),
('Bambang Wuryanto', ARRAY['Bambang Wuryanto','Bambang Pacul'], 'legislator', 'PDI-P', 'Anggota DPR', ARRAY['Era Jokowi'], true),
('Maruarar Sirait', ARRAY['Maruarar Sirait','Pak Maruarar'], 'legislator', 'PDI-P', 'Anggota DPR', ARRAY['Era Jokowi'], true),
('Utut Adianto', ARRAY['Utut Adianto','GM Utut'], 'legislator', 'PDI-P', 'Anggota DPR', ARRAY['Era Jokowi'], true),
('Sandiaga Salahudin Uno', ARRAY['Sandiaga Uno','Sandi','Pak Sandi'], 'legislator', 'PAN', 'Menparekraf (sebelumnya)', ARRAY['Era Jokowi'], true),
('Trimedya Panjaitan', ARRAY['Trimedya Panjaitan','Pak Trimedya'], 'legislator', 'PDI-P', 'Anggota DPR', ARRAY['Era Jokowi'], true),
('Tifatul Sembiring', ARRAY['Tifatul Sembiring','Pak Tifatul'], 'legislator', 'PKS', 'Menteri (sebelumnya)', ARRAY['Era SBY'], false),
('Tjokorda Oka Artha Ardhana Sukawati', ARRAY['Cok Ace','Tjokorda Oka Artha'], 'legislator', 'PDI-P', 'Anggota DPR', ARRAY['Era Jokowi'], true),
('Zainudin Amali', ARRAY['Zainudin Amali','Pak Zainudin'], 'legislator', 'Golkar', 'Menpora (sebelumnya)', ARRAY['Era Jokowi'], false),
('Yandri Susanto', ARRAY['Yandri Susanto'], 'legislator', 'PAN', 'Anggota DPR', ARRAY['Era Jokowi'], true),
-- F. MANTAN MENTERI/PEJABAT
('Luhut Binsar Pandjaitan', ARRAY['Luhut','Luhut Pandjaitan','Pak Luhut','LBP'], 'former_minister', 'Independen', 'Menko Marves (sebelumnya)', ARRAY['Era Jokowi'], false),
('Tito Karnavian', ARRAY['Tito Karnavian','Pak Tito','Jenderal Tito'], 'former_minister', 'Independen', 'Mendagri (sebelumnya)', ARRAY['Era Jokowi'], false),
('Mahfud MD', ARRAY['Mahfud MD','Pak Mahfud','Prof Mahfud'], 'former_minister', 'Independen', 'Menko Polhukam (sebelumnya)', ARRAY['Era Jokowi'], false),
('Yasonna Laoly', ARRAY['Yasonna Laoly','Pak Yasonna'], 'former_minister', 'PDI-P', 'Menkumham (sebelumnya)', ARRAY['Era Jokowi'], false),
('Siti Nurbaya', ARRAY['Siti Nurbaya','Bu Siti Nurbaya'], 'former_minister', 'NasDem', 'MenLHK (sebelumnya)', ARRAY['Era Jokowi'], false),
('Retno Marsudi', ARRAY['Retno Marsudi','Bu Retno'], 'former_minister', 'Independen', 'Menlu (sebelumnya)', ARRAY['Era Jokowi'], false),
('Rachmat Gobel', ARRAY['Rachmat Gobel','Pak Rachmat'], 'former_minister', 'PDI-P', 'Menteri Kesehatan (sebelumnya)', ARRAY['Era Jokowi'], false),
('Erick Thohir', ARRAY['Erick Thohir','Pak Erick'], 'former_minister', 'Independen', 'Menpora (sebelumnya)', ARRAY['Era Jokowi'], true),
('Ryamizard Ryacudu', ARRAY['Ryamizard Ryacudu','Pak Ryamizard'], 'former_minister', 'Independen', 'Menhan (sebelumnya)', ARRAY['Era SBY'], false),
('Tedjo Edhy Purdijatno', ARRAY['Tedjo Edhy','Pak Tedjo'], 'former_minister', 'NasDem', 'Menko Polhukam (sebelumnya)', ARRAY['Era Jokowi'], false),
('Moeldoko', ARRAY['Moeldoko','Pak Moeldoko'], 'former_minister', 'Independen', 'KSP (sebelumnya)', ARRAY['Era Jokowi'], false),
('Gatot Nurmantyo', ARRAY['Gatot Nurmantyo','Gatot','Jenderal Gatot'], 'former_minister', 'Berkarya', 'TNI AD (sebelumnya)', ARRAY['Era Jokowi'], false),
-- G. PENGAMAT & KOMENTATOR POLITIK
('Rocky Gerung', ARRAY['Rocky Gerung','Pak Rocky'], 'commentator', 'Independen', 'Pengamat Politik', ARRAY['Era Jokowi','Era Prabowo'], true),
('Yusril Ihza Mahendra', ARRAY['Yusril Ihza','Prof Yusril','Pak Yusril'], 'commentator', 'Independen', 'Pakar Hukum Tata Negara', ARRAY['Era SBY','Era Jokowi','Era Prabowo'], true),
('Refly Harun', ARRAY['Refly Harun','Pak Refly'], 'commentator', 'Independen', 'Pengamat Hukum', ARRAY['Era Jokowi'], true),
('Bonar Hutahean', ARRAY['Bonar Hutahean','Bonar'], 'commentator', 'Independen', 'Komentator Politik', ARRAY['Era Jokowi'], true),
('Fadjroel Rakman', ARRAY['Fadjroel Rakman'], 'commentator', 'Independen', 'Jubir Presiden (sebelumnya)', ARRAY['Era Jokowi'], false),
('Denni Nurjaman', ARRAY['Denni Nurjaman','Pak Denni'], 'commentator', 'Independen', 'Pengamat Politik', ARRAY['Era Jokowi'], true),
('Arief Budiman', ARRAY['Arief Budiman'], 'commentator', 'Independen', 'Pengamat Politik', ARRAY['Era SBY','Era Jokowi'], false),
('Riefqi Muna', ARRAY['Riefqi Muna','Pak Riefqi'], 'commentator', 'Independen', 'Pengamat Politik', ARRAY['Era Jokowi','Era Prabowo'], true),
('Ade Armando', ARRAY['Ade Armando','Pak Ade'], 'commentator', 'Independen', 'Komentator Politik', ARRAY['Era Jokowi'], true),
('Eep Saefulloh Fatah', ARRAY['Eep Saefulloh','Eep Fatah'], 'commentator', 'Independen', 'Pengamat Politik UGM', ARRAY['Era Jokowi'], true),
('Marcus Mietzner', ARRAY['Marcus Mietzner'], 'commentator', 'Independen', 'Pakar Politik (Australia)', ARRAY['Era SBY','Era Jokowi','Era Prabowo'], true),
('Burhanuddin Muhtadi', ARRAY['Burhanuddin Muhtadi','Burhan'], 'commentator', 'Independen', 'Pengamat Politik (Indikator)', ARRAY['Era Jokowi','Era Prabowo'], true),
-- H. AKTIVIS & INFLUENCER
('Haris Azhar', ARRAY['Haris Azhar','Haris'], 'influencer', 'Independen', 'Aktivis HAM', ARRAY['Era Jokowi'], true),
('Fatia Maulidiyanti', ARRAY['Fatia Maulidiyanti','Fatia'], 'influencer', 'Independen', 'Aktivis HAM', ARRAY['Era Jokowi'], true),
('Deddy Corbuzier', ARRAY['Deddy Corbuzier','Deddy','DC'], 'influencer', 'Independen', 'Podcaster & Influencer', ARRAY['Era Jokowi','Era Prabowo'], true),
-- I. TOKOH AGAMA & ORMAS
('Yahya Cholil Staquf', ARRAY['Yahya Cholil Staquf','Gus Yahya'], 'other', 'NU', 'Ketua Umum PBNU', ARRAY['Era Jokowi','Era Prabowo'], true),
('Said Aqil Siroj', ARRAY['Said Aqil Siroj','K.H. Said Aqil','SAS'], 'other', 'NU', 'Ketum PBNU (sebelumnya)', ARRAY['Era SBY','Era Jokowi'], false),
('Anwar Abbas', ARRAY['Anwar Abbas','Pak Anwar Abbas'], 'other', 'Muhammadiyah', 'Tokoh PP Muhammadiyah', ARRAY['Era Jokowi'], true),
('Haedar Nashir', ARRAY['Haedar Nashir','Prof Haedar Nashir'], 'other', 'Muhammadiyah', 'Ketum PP Muhammadiyah', ARRAY['Era Jokowi','Era Prabowo'], true),
('Din Syamsuddin', ARRAY['Din Syamsuddin','Prof Din Syamsuddin'], 'other', 'Muhammadiyah', 'Ketum PP Muhammadiyah (sebelumnya)', ARRAY['Era SBY','Era Jokowi'], false),
-- J. AKADEMISI & PAKAR
('Rizal Ramli', ARRAY['Rizal Ramli','Pak Rizal Ramli','Prof Rizal Ramli'], 'academic', 'Independen', 'Ekonom & Menteri (sebelumnya)', ARRAY['Era SBY','Era Jokowi'], false),
('Chatib Basri', ARRAY['Chatib Basri','Pak Chatib'], 'academic', 'Independen', 'Ekonom & Menkeu (sebelumnya)', ARRAY['Era SBY'], false),
('Faisal Basri', ARRAY['Faisal Basri','Pak Faisal Basri','Prof Faisal'], 'academic', 'Independen', 'Ekonom UI', ARRAY['Era SBY','Era Jokowi'], true),
('Bhima Yudhistira', ARRAY['Bhima Yudhistira','Bhima'], 'academic', 'Independen', 'Ekonom (CORE)', ARRAY['Era Jokowi','Era Prabowo'], true),
('Enny Sri Hartati', ARRAY['Enny Sri Hartati','Bu Enny'], 'academic', 'Independen', 'Ekonom IEWPI', ARRAY['Era Jokowi'], true),
('Rhenald Kasali', ARRAY['Rhenald Kasali','Pak Rhenald'], 'academic', 'Independen', 'Pakar Manajemen UI', ARRAY['Era SBY','Era Jokowi'], true),
-- K. BISNIS-K POLITIK
('Hary Tanoesoedibjo', ARRAY['Hary Tanoesoedibjo','HT','Hary Tanoe'], 'other', 'Perindo', 'Tokoh Media & Politik', ARRAY['Era SBY','Era Jokowi','Era Prabowo'], true),
('Aburizal Bakrie', ARRAY['Aburizal Bakrie','Ical','Bakrie'], 'other', 'Golkar', 'Tokoh Bisnis & Politik', ARRAY['Era SBY','Era Jokowi'], false),
('Rusdi Kirana', ARRAY['Rusdi Kirana','Pak Rusdi'], 'other', 'PKB', 'Tokoh Bisnis & Politik', ARRAY['Era Jokowi'], false),
-- L. MILITER & KEAMANAN
('Doni Monardo', ARRAY['Doni Monardo','Pak Doni'], 'former_official', 'Independen', 'BNPB (sebelumnya)', ARRAY['Era Jokowi'], false),
-- M. TOKOH LAINNYA
('Suharso Monoarfa', ARRAY['Suharso Monoarfa','Pak Suharso'], 'other', 'PPP', 'Menteri Bappenas (sebelumnya)', ARRAY['Era Jokowi'], false),
('Muhammad Romahurmuziy', ARRAY['Romahurmuziy','Romi'], 'other', 'PPP', 'Ketum PPP (sebelumnya)', ARRAY['Era Jokowi'], false),
('Ahmad Riza Patria', ARRAY['Ahmad Riza Patria','Pak Ahmad Riza'], 'other', 'Gerindra', 'Wagub DKI (sebelumnya)', ARRAY['Era Jokowi'], false)
ON CONFLICT (canonical_name) DO UPDATE SET
  aliases = EXCLUDED.aliases,
  entity_type = EXCLUDED.entity_type,
  party_affiliation = EXCLUDED.party_affiliation,
  position = EXCLUDED.position,
  era = EXCLUDED.era,
  is_active = EXCLUDED.is_active;
