name: RSS Backup, GNews, DDG & Enricher

on:
  schedule:
    - cron: '13 0 * * *'
    - cron: '19 5 * * *'
    - cron: '23 10 * * *'
    - cron: '41 15 * * *'
  workflow_dispatch:
jobs:
  trigger-rss:
    name: Trigger RSS Deno
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Supabase Edge Function
        run: |
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" --request POST \
          --header "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          --header "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
          "${{ secrets.SUPABASE_EDGE_FUNCTION_URL }}")
          if [ "$HTTP_STATUS" -ne 200 ]; then exit 1; fi

  run-fetchers:
    name: Run GNews & DDG Fetcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: pip install -r requirements.txt # Ini di root folder
      - name: Run GNews Fetcher
        run: python -m packages.ingestion.gnews_fetcher
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      - name: Run DDG Fetcher
        run: python -m packages.ingestion.ddg_fetcher
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}